version: '3.7'

services:
  nginx:
    container_name: angular-nginx
    image: soulou2019/angular-nginx
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - node_server
    networks:
      - myadmin-portal-network
   # command: ["node", "--inspect=0.0.0.0:9229", "index.js"]

  node_server:
    container_name: node-server
    image: soulou2019/node-server
    build:
      context: ./server
      dockerfile: node.server.dockerfile
    ports:
      - 3000:3000
    networks:
      - myadmin-portal-network

networks:
  myadmin-portal-network:
    driver: bridge
