# Define the backend service desired state
kind: Service
apiVersion: v1
metadata:
  name:  backend-service
  # namespace: misc
spec:
  selector:
    app:  backend
  type:  ClusterIP
  ports:
  - port:  80
    targetPort:  80