apiVersion: v1
entries:
  admin-portal:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2022-04-06T09:58:07.2925702+01:00"
    description: First draft of the chart with embedded backend API & DB, i.e. http-json
      server
    digest: ec61976b95acb529762062cd0fa5256e2ebc3b861e02339c035d2b25805b8565
    name: admin-portal
    type: application
    urls:
    - admin-portal-1.2.0.tgz
    version: 1.2.0
generated: "2022-04-06T09:58:07.290609+01:00"
